spring:
  datasource:
    url: ${DB2_URL:jdbc:db2://localhost:50000/CARTERA}
    username: ${DB2_USERNAME:db2inst1}
    password: ${DB2_PASSWORD:password}
    driver-class-name: com.ibm.db2.jcc.DB2Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DB2Dialect
    open-in-view: false
    show-sql: false
  jackson:
    serialization:
      write-dates-as-timestamps: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.cartera.cobranza: INFO
